name: vHunger
main: com.valygard.vhunger.Hunger
version: 1.2.2.76
author: AoH_Ruthless
website: http://valygard.com
commands:
  hunger:
    description: Base Command for vHunger.
permissions:
  hunger.user:
    default: true
    children:
      hunger.check: true
  hunger.admin:
    default: op
    children:
      hunger.set: true
      hunger.nohunger: true
      hunger.effects.exempt: true
      hunger.set.others: true
      hunger.nourish: true
      hunger.nourish.others: true
      hunger.user: true
      hunger.check.others: true
    